### ISSUE TITLE
Crash when attempt to add static image

### ISSUE THREAD

**Issue by x-st3v3n** [mendixlabs/carousel#21]
Using latest web modeler, dropping the carousel into a container, then attempting to configure a state image results in the web modeller crashing.

**Comment by Andries-Smit** [comment]
Dear Steven,

Thank you for reporting this issue to us, we will look into this.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Hi Steven,

We found the cause of the issue, we be working on a patch. The Mendix webmodeler is working on a solution to prevent this type of crashes.

We will let you know when a patch is released

Cheers,

**Comment by x-st3v3n** [comment]
Thats excellent, thanks.  I had a quicl look in web modeler and I can see it is looking better (not a fullt test, i'll do more later in the day).

Btw, the issue also occurs in the desktop modeler, so it will need fixing there as well.

Regards,
Steve

**Comment by Andries-Smit** [comment]
Hi Steve, 

We released the fix in v1.4.1 You can download from the app store, 
https://appstore.home.mendix.com/link/app/47784/

Please let me know if this will solve our issue.

Cheers,
Andries

**Comment by x-st3v3n** [comment]
Ah, lovely, it seems to be working.  I just updated the widget in WebModeler, re-published and all looks good.

Thanks !
