### ISSUE TITLE
Refresh of microflow

### ISSUE THREAD

**Issue by LST1977** [mendixlabs/carousel#23]
I'm using the carousel to display uploaded images of a user. Almost the same idea as the template grid. The problem is that when I call a popup to add an image to an association of an object and I return to the screen, the carousel does not "recall" the microflow and the new image is not shown. Refresh of the page does show the image afterwards. Therefor I think it is refresh related.

**Comment by Andries-Smit** [comment]
The widget was not intended to reload. Please make sure you refresh add a context object, in the context object the carousel can be placed. Refreshing the context should reload the carousel too. It also works in the development test project.
